[project]
name = "sheriff"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "TinasheMTapera", email = "tinashemtapera@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "path>=17.1.1",
]

[project.scripts]
sheriff-inspect = "sheriff.sheriff:main"

[build-system]
requires = ["uv_build>=0.11.7,<0.12.0"]
build-backend = "uv_build"
