[project]
name = "sheriff"
version = "0.1.1"
description = "A simple tool to validate frontier citizenship"
readme = "README.md"
authors = [
    { name = "TinasheMTapera", email = "tinashemtapera@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "globus-sdk>=4.5.0",
    "great-docs>=0.10.0",
    "ipykernel>=7.2.0",
    "jupyter>=1.1.1",
    "path>=17.1.1",
    "pyyaml>=6.0.3",
    "rich>=15.0.0",
    "ruff>=0.15.12",
    "typer>=0.25.1",
]

[project.scripts]
sheriff = "sheriff.sheriff:app"

[build-system]
requires = ["uv_build>=0.11.7,<0.12.0"]
build-backend = "uv_build"
